### ISSUE TITLE
Basic Hasura-based API as a service

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-api#4]
Epic here #1 

When developing data-api I want to be able to create and run integration tests of the app so that I can check how it's working together with postgres and hasura.

## Acceptance

* [x] There is a docker-compose environment with the necessary cervices
* [x] There is ci running tests and publishing to a Docker repository

### Local developer docker-compose

* [x] add services to docker-compose
  * [x] postres (latest official postgres image)
  * [x] hasura (custom image with adding sample data)
* [x] write a basic smoke test checking the system parts are working
  * [x] Find the framework to use (Supertest remains the default for node http server tests ...)

### CI

* [x] Dockerfile (`FROM nodejs ...` + copy files)
* [x] Publish Docker image (used https://github.com/datopian/data-api/new/master?filename=.github%2Fworkflows%2Fdocker-publish.yml&workflow_template=docker-publish for how to)
* [x] Add another docker-compose for ci
  * [x] add data-api image building from source (include tests)
* [x] check code correctness in CI on every push:
  * [x] run prettier
  * [x] run tests
* [ ] create new version Docker tags  automatically - CI on every push to master:
  * [ ] update version (if tests ok)
  * [ ] publish new version of the image
  * [x] publish :latest tag with the new changes

## Inbox

> * [ ] Have Hasura based read API
> * [ ] Dockerize this service and auto publish on merge to master
>   * [ ] Work out where we publish to (is it dockerhub or is it github packages? (Ask on tech help?)
>   * [ ] Publish there with continuous deployment (on master) 
> * [ ] Testing
>   * [ ] Have basic test for this (using cypress (?))
>   * [ ] CI setup and passing

**Comment by EvgeniiaVak** [comment]
@rufuspollock I don't think we really need to store hasura settings anywhere or publish a custom hasura image, because what we will set up in hasura is 
* mark which tables we want to track ([hasura metadata](https://hasura.io/docs/1.0/graphql/core/migrations/manage-metadata.html#manage-hasura-metadata)) 
* run any sql scripts preparing tables/views ([hasura migrations](https://hasura.io/docs/1.0/graphql/core/migrations/migrations-setup.html#migrations-setup))

That is very project specific, I don't think we can have anything Datopian wide here. We can just launch hasura service in a project (like we would launch postgres):

#### Example Hasura Dockerfile

```Dockerfile
FROM hasura/graphql-engine:latest.cli-migrations-v2

COPY migrations /hasura-migrations/
COPY metadata /hasura-metadata/
```

#### Example docker-compose containing Postgres, Hasura, A third service

```yml
version: '3'
services:
  wrapper:
    image: my-app-wrapper
    build:
      context: wrapper/
      dockerfile: Dockerfile

  graphql-engine:
    image: my-app-hasura
    build:
      context: hasura/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://ckan_default:password@db:5432/datastore_default
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  db:
    image: my-app-postgres
    build:
      context: postgres/
      dockerfile: Dockerfile
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: datastore_default
      POSTGRES_USER: ckan_default
      POSTGRES_PASSWORD: password
```
